In [1]:
import pandas as pd
import re

In [2]:
final_df = pd.read_csv('./final_df.csv',low_memory=False)
final_df = final_df.applymap(lambda s:s.lower() if type(s) == str else s)

In [3]:
def search(df = final_df, text = None,columns = ['Continent', 'Country', 'Region', 'Cultural Group', 'Local name', 'Keywords for printouts', 'Class for printouts', 'Processes for printouts', 'Materials for printouts', 'Date made', 'Field Collector', 'When collected', 'PRM Source', 'Acquired'], incomplete_columns=['PRM Source', 'Description', 'Research notes', 'Publications history', 'Primary documentation']):
    text = re.findall(r'(\w+)',text)
    c=0
    
    for i in columns:
       # print(i)
        if c==0:
            if len(df[df[i].str.contains('|'.join(text))==True])>0:
             #   print(len(df[df[i].str.contains('|'.join(text))==True]))
                appa = df[df[i].str.contains('|'.join(text))==True]
                c+=1
            else:
                pass
        else:
            appa.append(df[df[i].str.contains('|'.join(text))==True])
    
    appa['ALL']= ''
    for i in incomplete_columns:
        appa['ALL']= appa['ALL'] + appa[i]
    
    appa['ALL'] = appa['ALL'].str.len()*1
    appa['ALL'].fillna(0, inplace=True)
    appa = appa.sort_values('ALL')
    appa.drop_duplicates(keep='first',inplace = True)
    
    return appa
    

    
    
def year(df= final_df,Before = False, value=1940):
    
    
    if Before == True:
        
        
        return df[df['Accession_Number_Year']<=value]
    else:
        return df[df['Accession_Number_Year']>=value]

In [4]:
search(text='africa')

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/generic.py:5434: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

,Unnamed: 0,Accession Number,Accession Book,Maker,Date made,Field Collector,When collected,Other Owners,Documentation,Related Collections,...,Unnamed: 4_class_,Unnamed: 5_class_,Unnamed: 6_class_,Unnamed: 7_class_,Unnamed: 8_class_,Country,Acquired_year,Accession_Number_Year,Date_made_year,ALL
2,2,1986.12.11,NaN,NaN,by 1972,mrs r.p. edwards,1972,mrs r. p. edwards purchased in 1972,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,ethiopia,1986.0,1986.0,1972.0,0.0
6906,6906,1900.74.2,purchases b i 130,NaN,by 1900,unknown,by 1900,george fabian lawrence,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1900.0,1900.0,1900.0,0.0
6907,6907,1900.32.4,iii 10,NaN,by 1900,unknown,by 1900,harold st. george gray,NaN,NaN,...,?.,NaN,NaN,NaN,NaN,nigeria,1900.0,1900.0,1900.0,0.0
6908,6908,1909.67.23,purchases b ii 123,NaN,by 1909,northcote whitbridge thomas,1909,northcote whitbridge thomas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1909.0,1909.0,1909.0,0.0
6909,6909,1966.1.636,ipswich ethnography [a] 204,NaN,by 1928,?ethel charlotte bedford ?frederick george den...,by 1928,ethel charlotte bedford ipswich museum,see rdf.,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria?,1966.0,1966.0,1928.0,0.0
6910,6910,1966.1.639,ipswich ethnography [a] 205 - 206,NaN,by 1928,?ethel charlotte bedford ?frederick george den...,by 1928,ethel charlotte bedford ipswich museum,see rdf.,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria?,1966.0,1966.0,1928.0,0.0
6911,6911,1966.1.638,ipswich ethnography [a] 205a - 205,NaN,by 1928,?ethel charlotte bedford ?frederick george den...,by 1928,ethel charlotte bedford ipswich museum,see rdf.,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria?,1966.0,1966.0,1928.0,0.0
6912,6912,1966.1.637,ipswich ethnography [a] 205,NaN,by 1928,?ethel charlotte bedford ?frederick george den...,by 1928,ethel charlotte bedford ipswich museum,see rdf.,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria?,1966.0,1966.0,1928.0,0.0
6913,6913,1909.67.16,purchases b ii 122,NaN,by 1909,northcote whitbridge thomas,1909,northcote whitbridge thomas,NaN,NaN,...,?.,NaN,NaN,NaN,NaN,nigeria,1909.0,1909.0,1909.0,0.0
6914,6914,1909.67.15,purchases b ii 122,NaN,by 1909,northcote whitbridge thomas,1909,northcote whitbridge thomas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1909.0,1909.0,1909.0,0.0
6915,6915,1978.6.17,xxv 140,NaN,by 1908,t.m. russell-leonard,1907 - 1908,t.m. russell-leonard mr and mrs t.f.g. hopk...,NaN,NaN,...,?status,?ceremonial,?.,NaN,NaN,nigeria,1978.0,1978.0,1908.0,0.0
6916,6916,1909.1.2,iv 90,NaN,by 1909,henry nilus thompson,by 1909,henry nilus thompson,NaN,NaN,...,?.,NaN,NaN,NaN,NaN,nigeria,1909.0,1909.0,1909.0,0.0
6917,6917,1979.8.1,xxv 171,NaN,by circa 1897-8,reginald kerr granville,circa 1897- 1898,reginald kerr granville john granville,collector's diary in prm archives. corresponde...,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1979.0,1979.0,1897.0,0.0
6918,6918,1978.6.15,xxv 139 - 140,NaN,by 1908,t.m. russell-leonard,1907 - 1908,t.m. russell-leonard mr and mrs t.f.g. h...,NaN,NaN,...,weapon,?.,NaN,NaN,NaN,nigeria,1978.0,1978.0,1908.0,0.0
6919,6919,1978.6.16,xxv 140,NaN,by 1908,t.m. russell-leonard,1907 - 1908,t.m. russell-leonard mr and mrs t.f.g. hopki...,NaN,NaN,...,?status,weapon,?.,NaN,NaN,nigeria,1978.0,1978.0,1908.0,0.0
6920,6920,1909.67.3,purchases b ii 122,NaN,by 1909,northcote whitbridge thomas,1909,northcote whitbridge thomas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1909.0,1909.0,1909.0,0.0
6921,6921,1909.67.28,purchases b ii 123,NaN,by 1909,northcote whitbridge thomas,1909,northcote whitbridge thomas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1909.0,1909.0,1909.0,0.0
6922,6922,1909.67.2,purchases b ii 122,NaN,by 1909,northcote whitbridge thomas,1909,northcote whitbridge thomas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1909.0,1909.0,1909.0,0.0
6923,6923,1909.67.1,purchases b ii 122,NaN,by 1909,northcote whitbridge thomas,1909,northcote whitbridge thomas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1909.0,1909.0,1909.0,0.0
6924,6924,1909.67.17,purchases b ii 122,NaN,by 1909,northcote whitbridge thomas,1909,northcote whitbridge thomas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1909.0,1909.0,1909.0,0.0
6905,6905,1900.74.3,purchases b i 130,NaN,by 1900,unknown,by 1900,george fabian lawrence,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1900.0,1900.0,1900.0,0.0
6925,6925,1900.39.23 .1 1900.39.23 .2,iii 15,NaN,by 1897,benin city punitive expedition,february 1897,mary henrietta kingsley,NaN,NaN,...,vessel,food,?.,NaN,NaN,nigeria,1900.0,1900.0,1897.0,0.0
6903,6903,1909.67.24,purchases b ii 123,NaN,by 1909,northcote whitbridge thomas,1909,northcote whitbridge thomas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1909.0,1909.0,1909.0,0.0
6900,6900,1900.39.17,iii 15,NaN,by 1897,benin city punitive expedition,february 1897,mary henrietta kingsley,old label in rdf.,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1900.0,1900.0,1897.0,0.0
6870,6870,1920.86.2,loans i 30,NaN,by 1920,?f. winter,by 1920,f. winter,"for illustration see: f.winter ""die kämme alle...",NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1920.0,1920.0,1920.0,0.0
6871,6871,1921.94.2,talbot 46 & vi 232,NaN,by 1921,percy amaury talbot ?,by 1921,percy amaury talbot,NaN,NaN,...,?.,NaN,NaN,NaN,NaN,nigeria,1921.0,1921.0,1921.0,0.0
6872,6872,1982.1.3,xxvi 145,NaN,?1920 - 1930,?margery perham,by 1982,margery perham,NaN,NaN,...,?.,NaN,NaN,NaN,NaN,nigeria,1982.0,1982.0,1920.0,0.0
6873,6873,1909.67.9,purchases b ii 122,NaN,by 1909,northcote whitbridge thomas,1909,northcote whitbridge thomas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1909.0,1909.0,1909.0,0.0
6874,6874,1941.10.90,xi 31,NaN,circa 1905,w.f. manners,circa 1905,miss manners w.f. manners,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1941.0,1941.0,1905.0,0.0
6875,6875,1900.39.22,iii 15,NaN,by 1897,benin city punitive expedition,february 1897,mary henrietta kingsley,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1900.0,1900.0,1897.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6884,6884,1909.67.32,purchases b ii 123,NaN,by 1909,northcote whitbridge thomas,1909,northcote whitbridge thomas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1909.0,1909.0,1909.0,1406.0
7423,7423,1991.13.26,NaN,NaN,by 1897,george le clerc egerton benin city punitive ex...,1897,NaN,see rdf for lists and notes.,field diary and photocopy of relevant sections...,...,NaN,NaN,NaN,NaN,NaN,nigeria,1991.0,1991.0,1897.0,1420.0
7406,7406,1991.13.3,NaN,mappin & webb,by 1897,george le clerc egerton benin city punitive ex...,1897,oba ovonrramwen ?,see rdf for lists and notes. ...,field diary and photocopy of relevant sections...,...,writing,?.,NaN,NaN,NaN,nigeria,1991.0,1991.0,1897.0,1426.0
7419,7419,1991.13.17 .1 1991.13.17 .2,NaN,NaN,by 1897,george le clerc egerton benin city punitive ex...,1897,NaN,see rdf for lists and notes.,field diary and photocopy of relevant sections...,...,insignia,religion,?.,NaN,NaN,nigeria,1991.0,1991.0,1897.0,1654.0
7409,7409,1991.13.6,NaN,NaN,by 1897,george le clerc egerton benin city punitive ex...,1897,NaN,see rdf for lists and notes.,field diary and photocopy of relevant sections...,...,?.,NaN,NaN,NaN,NaN,nigeria,1991.0,1991.0,1897.0,1670.0
7424,7424,1991.13.27 .1 1991.13.27 .2,NaN,NaN,by 1897,george le clerc egerton benin city punitive ex...,1897,NaN,see rdf for lists and notes.,field diary and photocopy of relevant sections...,...,NaN,NaN,NaN,NaN,NaN,nigeria,1991.0,1991.0,1897.0,1693.0
6882,6882,1932.88.863,balfour 3 33,NaN,by 1897,benin city punitive expedition,1897,henry balfour,see notes field.,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1932.0,1932.0,1897.0,1757.0
6840,6840,1901.54.1,purchases b ii 2,NaN,by 1897,unknown,1897,NaN,NaN,NaN,...,weapon,?.,NaN,NaN,NaN,nigeria,1901.0,1901.0,1897.0,1775.0
970,970,1987.25.1,NaN,NaN,by 1888,kate theresa escombe,by 1888,"an anonymous old hunter, until 1888; from 1888...",letter from donor in rdf.,NaN,...,NaN,NaN,NaN,NaN,NaN,south africa,1987.0,1987.0,1888.0,1801.0
3443,3443,1988.39.25,NaN,NaN,NaN,?robert de rustafjaell,1910,"robert de rustafjaell, luxor trading company, ...",list of original collection in rdf.,NaN,...,NaN,NaN,NaN,NaN,NaN,egypt,1988.0,1988.0,NaN,1888.0
3444,3444,1988.39.26,NaN,NaN,NaN,?robert de rustafjaell,1910,"robert de rustafjaell, luxor trading company, ...",list of original collection in rdf.,NaN,...,NaN,NaN,NaN,NaN,NaN,egypt,1988.0,1988.0,NaN,1906.0
3442,3442,1988.39.24,NaN,NaN,NaN,?robert de rustafjaell,1910,"robert de rustafjael, luxor trading company, u...",list of original collection in rdf.,NaN,...,NaN,NaN,NaN,NaN,NaN,egypt,1988.0,1988.0,NaN,1906.0
6927,6927,1975.7.2,xxiv 114 - 115,NaN,by 1897,unknown,1897 ?,augustus henry lane fox pitt rivers; farnham m...,"see corresp. file 202.4, vol. ii, `purchase gr...",NaN,...,?.,NaN,NaN,NaN,NaN,nigeria,1975.0,1975.0,1897.0,2013.0
6869,6869,1908.18.13,iv 74,NaN,by 1908,?william fingland,by 1908,william fingland,rdf,NaN,...,?.,NaN,NaN,NaN,NaN,nigeria,1908.0,1908.0,1908.0,2044.0
3445,3445,1988.39.27,NaN,NaN,NaN,robert de rustafjaell,1910,"robert de rustafjaell, luxor trading company, ...",list of original collection in rdf.,NaN,...,NaN,NaN,NaN,NaN,NaN,egypt,1988.0,1988.0,NaN,2091.0
6891,6891,1909.67.21,purchases b ii 123,NaN,by 1909,northcote whitbridge thomas,1909,northcote whitbridge thomas,NaN,maa cambridge g.i. jones negative (n.61207.gij...,...,religion,?.,NaN,NaN,NaN,nigeria,1909.0,1909.0,1909.0,2109.0
6888,6888,1900.39.9,iii 14,NaN,by 1897,benin city punitive expedition,february 1897,mary henrietta kingsley,NaN,NaN,...,religion,?.,NaN,NaN,NaN,nigeria,1900.0,1900.0,1897.0,2193.0
6886,6886,1900.39.7 [formerly misnumbered with 1900.37.7],iii 14,NaN,by 1897,benin city punitive expedition,february 1897,mary henrietta kingsley,NaN,NaN,...,religion,?.,NaN,NaN,NaN,nigeria,1900.0,1900.0,1897.0,2277.0
7427,7427,1991.13.31,NaN,george leclerc egerton,1897,george le clerc egerton benin city punitive ex...,1897,NaN,"see rdf for lists, notes etc.",field diary and photocopy of relevant sections...,...,NaN,NaN,NaN,NaN,NaN,nigeria,1991.0,1991.0,1897.0,2433.0
6877,6877,1975.7.1,xxiv 113 - 114,NaN,by 1897,unknown,1897 ?,william downing webster; augustus henry lane f...,"see file 202.4, vol ii, `purchase grants', and...",NaN,...,furniture dwelling,weapon,?.,NaN,NaN,nigeria,1975.0,1975.0,1897.0,2456.0
6879,6879,1967.45.1,xxi 154 - 155,NaN,by circa 1920,hugh nevin nevins,1920s,NaN,correspondence with donor in rdf. see also col...,photographs and papers from nevins in prm arch...,...,?.,NaN,NaN,NaN,NaN,nigeria,1967.0,1967.0,1920.0,2746.0
6850,6850,1900.39.3,iii 14,NaN,by 1897,benin city punitive expedition,february 1897,mary henrietta kingsley,note by frank willett in rdf; also letter from...,NaN,...,?.,NaN,NaN,NaN,NaN,nigeria,1900.0,1900.0,1897.0,2930.0
6858,6858,1907.66.1,purchases b ii 89,NaN,circa 1500 - 1700,f. embury,by 1907,f. embury,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1907.0,1907.0,1500.0,2985.0
7430,7430,1991.13.36,NaN,NaN,by 1897,george le clerc egerton benin city punitive ex...,1897,NaN,see rdf for lists and notes.,field diary and photocopy of relevant sections...,...,NaN,NaN,NaN,NaN,NaN,nigeria,1991.0,1991.0,1897.0,3007.0
6926,6926,1900.39.4,iii 14,NaN,circa 1700-1800,felix norman ling roth benin city punitive exp...,february 1897,felix norman ling roth; mary henrietta kingsley,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1900.0,1900.0,1700.0,3583.0
7422,7422,1991.13.25,NaN,NaN,? 1750 - 1850,george le clerc egerton benin city punitive ex...,1897,NaN,see rdf for lists and notes.,field diary and photocopy of relevant sections...,...,NaN,NaN,NaN,NaN,NaN,nigeria,1991.0,1991.0,1750.0,3718.0
6932,6932,1923.2.1,vii 65,NaN,1500 - 1700,?percy amaury talbot,by 1923,percy amaury talbot,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,nigeria,1923.0,1923.0,1500.0,3814.0
7411,7411,1991.13.8,NaN,NaN,circa 1500 - 1700,george le clerc egerton benin city punitive ex...,1897,NaN,see rdf for lists and notes. ...,field diary and photocopy of relevant sections...,...,NaN,NaN,NaN,NaN,NaN,nigeria,1991.0,1991.0,1500.0,3876.0
6876,6876,1909.1.1,iv 90,NaN,reign of adolo (1850–1888) or ovonranmwen (188...,henry nilus thompson,by 1909,henry nilus thompson,correspondence and notes in rdf.,NaN,...,status,?.,NaN,NaN,NaN,nigeria,1909.0,1909.0,1850.0,4250.0
9827,9827,1993.19.1,NaN,[f. christol; g. horrell],by 1993,unknown,by 1993,miss g. horrell ?,prm postcard in rdf.,NaN,...,NaN,NaN,NaN,NaN,NaN,lesotho,1993.0,1993.0,1993.0,5431.0